### ISSUE TITLE
Crash related to this mod

### ISSUE THREAD

**Issue by Block-Vader** [bageldotjpg/Atmospheric#11]
I was exploring my world with a map in my offhand, when my game crashed. Every time I loaded that world the game crashed after a few seconds. I tried to removing all mods I had one by one to find out which one is responsible for the crash and it turned out it was Atmospheric.

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 18.4.20 23:25
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[guava-21.0.jar:?] {}
	at com.google.common.collect.RegularImmutableMultiset.<init>(RegularImmutableMultiset.java:68) ~[guava-21.0.jar:?] {}
	at com.google.common.collect.ImmutableMultiset.copyFromEntries(ImmutableMultiset.java:218) ~[guava-21.0.jar:?] {}
	at com.google.common.collect.Multisets.copyHighestCountFirst(Multisets.java:1137) ~[guava-21.0.jar:?] {}
	at net.minecraft.item.FilledMapItem.func_77872_a(FilledMapItem.java:192) ~[?:?] {re:classloading}
	at net.minecraft.item.FilledMapItem.func_77663_a(FilledMapItem.java:336) ~[?:?] {re:classloading}
	at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:414) ~[?:?] {re:classloading,xf:fml:quark:add-spacing-for-stack}
	at net.minecraft.entity.player.PlayerInventory.func_70429_k(PlayerInventory.java:265) ~[?:?] {re:classloading}
	at net.minecraft.entity.player.PlayerEntity.func_70636_d(PlayerEntity.java:505) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2104) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:233) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:361) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:183) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:228) ~[?:?] {re:classloading}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:866) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at com.google.common.collect.RegularImmutableMultiset.<init>(RegularImmutableMultiset.java:68)
	at com.google.common.collect.ImmutableMultiset.copyFromEntries(ImmutableMultiset.java:218)
	at com.google.common.collect.Multisets.copyHighestCountFirst(Multisets.java:1137)
	at net.minecraft.item.FilledMapItem.func_77872_a(FilledMapItem.java:192)
	at net.minecraft.item.FilledMapItem.func_77663_a(FilledMapItem.java:336)
	at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:414)
	at net.minecraft.entity.player.PlayerInventory.func_70429_k(PlayerInventory.java:265)
	at net.minecraft.entity.player.PlayerEntity.func_70636_d(PlayerEntity.java:505)
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2104)
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:233)

-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.entity.player.ServerPlayerEntity)
	Entity ID: 55
	Entity Name: Fcelon
	Entity's Exact location: -30.99, 67.00, -1004.48
	Entity's Block location: World: (-31,67,-1005), Chunk: (at 1,4,3 in -2,-63; contains blocks -32,0,-1008 to -17,255,-993), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:361)
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:183)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:228)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@51e43a
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:866)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3640309248 bytes (3471 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.36.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.36.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.4-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.36.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.36.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.36.jar fml TRANSFORMATIONSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.36
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		forge-1.15.2-31.1.36-client.jar Minecraft {minecraft@1.15.2 DONE}
		wt_improvements-1.0.jar Wandering trader improvements {wt_improvements@1.0 DONE}
		QuarkOddities-1.15.2.jar Quark Oddities {quarkoddities@1.15.2 DONE}
		swingthroughgrass-1.15.2-1.4.0.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.0 DONE}
		berry_good-2.0.0.jar Berry Good {berry_good@2.0 DONE}
		bambooblocks-1.15.2-1.3.jar Bamboo Blocks {bambooblocks@1.2.11 DONE}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 DONE}
		buzzierbees-1.4.jar Buzzier Bees {buzzierbees@1.4 DONE}
		atmospheric-1.15.2-1.2.1.jar Atmospheric {atmospheric@1.2.1 DONE}
		Upgrade-Aquatic-1.15.2-v1.5.1.jar Upgrade Aquatic {upgrade_aquatic@1.5.1 DONE}
		bloomful-1.15.2-1.3.2.jar Bloomful {bloomful@NONE DONE}
		extraboats-1.3.2-1.15.2.jar Extra Boats {extraboats@1.3.2 DONE}
		TerraForged-1.15.2-0.0.10.jar TerraForged {terraforged@0.0.10 DONE}
		lava-monster-1.15.2-1.0.3.jar Lava Monster {lava_monster@1.0.3 DONE}
		autumnity-1.1.0-1.15.2.jar Autumnity {autumnity@1.1.0 DONE}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 DONE}
		AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 DONE}
		beaconsforall-FORGE-1.15.2-3.0.jar Beacons For All {beaconsforall@FORGE-1.15.2-3.0 DONE}
		The-Endergetic-Expansion-1.15.2-v1.2.5.jar The Endergetic Expansion {endergetic@1.2.1 DONE}
		ToastControl-1.15.2-3.0.1.jar Toast Control {toastcontrol@3.0.1 DONE}
		SnowRealMagic-1.15.2-1.7.4.jar Snow! Real Magic! {snowrealmagic@1.7.4 DONE}
		Kiwi-1.15.2-2.6.5.jar Kiwi {kiwi@2.6.5 DONE}
		VTweaks-1.15.2-3.1.6.jar V-Tweaks {vtweaks@3.1.5 DONE}
		swampexpansion-1.15.2-1.5.1.jar Swamp Expansion {swampexpansion@NONE DONE}
		forge-1.15.2-31.1.36-universal.jar Forge {forge@31.1.36 DONE}
		Quark-r2.1-231.jar Quark {quark@r2.1-231 DONE}
		cofh_core-1.15.2-0.3.2b.jar CoFH Core {cofh_core@0.3.2b DONE}
		ensorcellation-1.15.2-0.3.0b.jar Ensorcellation {ensorcellation@0.3.0b DONE}
		respawnablepets-1.0.6.4.jar Respawnable Pets {respawnablepets@1.0.6.4 DONE}
		incubation-1.0.2-1.15.2.jar Incubation {incubation@1.0.2 DONE}
	Kiwi Modules: 
		kiwi:contributors
		snowrealmagic:snowrealmagic
	Player Count: 1 / 8; [ServerPlayerEntity['Fcelon'/55, l='Slightly better vanilla', x=-30.99, y=67.00, z=-1004.48]]
	Data Packs: vanilla, mod:autoreglib (incompatible), mod:beaconsforall (incompatible), mod:buzzierbees, mod:cofh_core (incompatible), mod:ensorcellation (incompatible), mod:forge (incompatible), mod:jei (incompatible), mod:kiwi, mod:lava_monster (incompatible), mod:placebo (incompatible), mod:quark, mod:quarkoddities, mod:snowrealmagic, mod:swampexpansion (incompatible), mod:swingthroughgrass (incompatible), mod:terraforged, mod:toastcontrol (incompatible), mod:atmospheric, mod:autumnity, mod:bambooblocks (incompatible), mod:berry_good (incompatible), mod:bloomful (incompatible), mod:endergetic (incompatible), mod:extraboats, mod:incubation, mod:respawnablepets, mod:upgrade_aquatic (incompatible), mod:vtweaks (incompatible), mod:wt_improvements
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by Giustitia** [comment]
Same bug happened to me. Hope they fix it :D
